kind: pipeline
type: kubernetes
name: dnscontrol

steps:
  - name: build-push-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    settings:
      from_secret: docker_secret
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: drone_aws_access_key_id
      DRONE_AWS_SECRET_ACCESS_KEY:
        from_secret: drone_aws_secret_access_key
    commands:
      - sleep 5 # give docker enough time to start
      - docker build . -t veriganet:latest
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 776553443280.dkr.ecr.eu-west-1.amazonaws.com
      - docker tag veriganet:latest 776553443280.dkr.ecr.eu-west-1.amazonaws.com/veriganet:latest
      - docker push 776553443280.dkr.ecr.eu-west-1.amazonaws.com/veriganet:latest
    when:
      event:
        - push

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}