kind: pipeline
type: kubernetes
name: dnscontrol

steps:
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      from_secret: docker_secret
    commands:
      - docker build . -t veriganet:latest
    when:
      event:
        - push

volumes:
- name: dockersock
  hostPath:
    path: /var/run/docker.sock
    type: Socket
