site_name: verigaNET Documentation

theme:
  name: material
  locale: en
  features:
    - content.tabs.link
    - navigation.indexes
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - search.share
    - search.suggest
    - content.tabs.link
    - navigation.indexes
    - navigation.expand
    - toc.integrate
  palette:
    - scheme: nano
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: 'Noto Sans'
    code: 'Roboto Mono'
  icon:
    repo: 'fontawesome/brands/github'

plugins:
  - search