apiVersion: skaffold/v2beta26
kind: Config
profiles:
  - name: pre
    deploy:
      kubectl:
        manifests:
          - ./pre.yaml
  - name: stg
    deploy:
      helm:
        releases:
          - name: veriganet-stg
            chartPath: ./helm-charts/veriganet
            namespace: veriganet-stg
            setValues:
              web.image.tag: stg
              web.ingress.host: stg.veriga.net
              vault.role: veriganet
  - name: prod
    deploy:
      helm:
        releases:
          - name: veriganet
            chartPath: ./helm-charts/veriganet
            namespace: veriganet
            setValues:
              web.image.tag: latest
              web.ingress.host: veriga.net
