replicaCount: 2

image:
  repository: veriganet/veriganet
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"
