vault:
  role: veriganet

web:
  replicaCount: 2

  image:
    repository: veriganet/veriganet
    tag: latest
    pullPolicy: IfNotPresent

  ingress:
    enabled: true
    ingressClassName: nginx
    host:

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

docs:
  replicaCount: 2

  image:
    repository: veriganet/veriganet
    tag: docs-latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"