{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ .Chart.Name }}
              servicePort: {{ .Values.service.port }}
    - host: www.{{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ .Chart.Name }}
              servicePort: {{ .Values.service.port }}
{{- end }}
